name: Build

on:
  push:
    branches: ["v0.5-hotfix"]
  pull_request:
    branches: ["v0.5-hotfix"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build GameYob
        run: |
          make
          mkdir -p ~/artifacts
          cp gameyob.nds ~/artifacts
          cp gameyob_dsi.nds.cia ~/artifacts
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
