name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_generate_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html
        keep_files: true
