name: Generate Doxygen Documentation

on:
  push:
    branches: ["v0.5-hotfix"]
  pull_request:
    branches: ["v0.5-hotfix"]
  workflow_dispatch:

jobs:
  build_and_generate_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Doxygen and Graphviz
      run: sudo apt-get install doxygen graphviz

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Documentation
